# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-15 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180511_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
