# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.TextField(null=True),
        ),
    ]
