# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_studentcourseenrolledmodel'),
        ('students', '0002_studentcoursemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconstraintsmodel',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseModel'),
            preserve_default=False,
        ),
    ]
