# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentconstraintsmodel_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursemodel',
            name='enrollment_status',
            field=models.BooleanField(default=True),
        ),
    ]
