# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraints',
            name='options',
            field=models.TextField(),
        ),
    ]
