# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHomeWorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_name', models.TextField()),
                ('grade_deadline', models.DateField()),
                ('homework_deadline', models.DateField()),
                ('constraints', models.TextField()),
                ('attachment', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseModel')),
            ],
            options={
                'db_table': 'course_homework',
            },
        ),
    ]
