# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_coursehomeworkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehomeworkmodel',
            name='attachment',
            field=models.TextField(null=True),
        ),
    ]
