# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-20 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20180520_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseEnrolledModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseModel')),
            ],
            options={
                'db_table': 'course_student',
            },
        ),
    ]
