# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-24 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0005_studentcourseenrolledmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseModel')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseHomeWorkModel')),
            ],
            options={
                'db_table': 'homework_group_master',
            },
        ),
        migrations.CreateModel(
            name='HomeworkGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homework_group_member',
            },
        ),
    ]
