# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-26 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0006_homeworkgroup_homeworkgroupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkgroupmember',
            name='user',
        ),
        migrations.AddField(
            model_name='homeworkgroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HomeworkGroupMember',
        ),
    ]
