# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-26 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0007_auto_20180526_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'homework_group_member',
            },
        ),
        migrations.AlterField(
            model_name='homeworkgroup',
            name='group',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='homeworkgroup',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworkgroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.HomeworkGroup', to_field='group'),
        ),
        migrations.AddField(
            model_name='homeworkgroupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
