# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_remove_homeworkgroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkgroup',
            name='grade',
            field=models.TextField(default=0),
        ),
    ]
