# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-26 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0010_homeworkgroup_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkGroupGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.TextField(default=0)),
                ('explanation', models.TextField(null=True)),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homework_group_grade',
            },
        ),
        migrations.RemoveField(
            model_name='homeworkgroup',
            name='grade',
        ),
        migrations.AddField(
            model_name='homeworkgroup',
            name='attachments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeworkgroupgrade',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.HomeworkGroup', to_field='group'),
        ),
    ]
