# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0011_auto_20180526_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCombinationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseModel')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group1', to='instructor.HomeworkGroup', to_field='group')),
                ('group2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group2', to='instructor.HomeworkGroup', to_field='group')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseHomeWorkModel')),
            ],
            options={
                'db_table': 'group_group_combination',
            },
        ),
    ]
