# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0013_groupcombinationmodel_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcombinationmodel',
            old_name='group2',
            new_name='grader_group',
        ),
        migrations.RenameField(
            model_name='groupcombinationmodel',
            old_name='grader',
            new_name='grader_user',
        ),
        migrations.RenameField(
            model_name='groupcombinationmodel',
            old_name='group1',
            new_name='group',
        ),
    ]
