# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-30 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0014_auto_20180529_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkgroup',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
