# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0015_auto_20180530_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcombinationmodel',
            name='peerevalutation',
            field=models.BooleanField(default=False),
        ),
    ]
