# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-21 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0016_groupcombinationmodel_peerevalutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkgroup',
            name='appeal_done_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeworkgroup',
            name='total_member',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupcombinationmodel',
            name='grader_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
