# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0019_homeworkgroup_appeal_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealGraderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_explanation', models.TextField()),
                ('grade', models.IntegerField()),
                ('appeal_grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.HomeworkGroup', to_field='group')),
            ],
            options={
                'db_table': 'appeal_grader_master',
            },
        ),
    ]
