# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0020_appealgradermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkgroup',
            old_name='appeal_canceled',
            new_name='appeal_done_status',
        ),
    ]
