# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0021_auto_20180622_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkgroup',
            name='appeal_done_status',
            field=models.BooleanField(default=True),
        ),
    ]
