# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0022_auto_20180622_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkgroupmember',
            name='has_appealed',
            field=models.BooleanField(default=False),
        ),
    ]
