# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0023_homeworkgroupmember_has_appealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealgradermodel',
            name='appeal_by_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appeal_by_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appealgradermodel',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
