# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0025_appealgradermodel_appeal_visible_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealgradermodel',
            name='appeal_grader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
