# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0026_auto_20180623_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkgroup',
            name='appeal_reject_status',
            field=models.BooleanField(default=False),
        ),
    ]
