# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0027_homeworkgroup_appeal_reject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealgradermodel',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseModel'),
            preserve_default=False,
        ),
    ]
