# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0029_peerevaluationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerevaluationmodel',
            name='homework',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseHomeWorkModel'),
            preserve_default=False,
        ),
    ]
