# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0030_peerevaluationmodel_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealgradermodel',
            name='appeal_reason',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
