# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0031_appealgradermodel_appeal_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkgroup',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
