# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0032_homeworkgroup_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkgroupgrade',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
