# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0033_auto_20180624_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehomeworkmodel',
            name='no_of_grader',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursehomeworkmodel',
            name='no_of_group',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coursehomeworkmodel',
            name='grade_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coursehomeworkmodel',
            name='homework_deadline',
            field=models.DateTimeField(),
        ),
    ]
