# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0035_auto_20180703_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursehomeworkmodel',
            old_name='no_of_grade',
            new_name='no_of_grader',
        ),
    ]
