# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0038_auto_20180707_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkgroup',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
