# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0039_auto_20180708_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealgradermodel',
            name='appeal_grading_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appealgradermodel',
            name='appeal_peer_grading_status',
            field=models.BooleanField(default=False),
        ),
    ]
