# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-09 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0040_auto_20180708_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcombinationmodel',
            name='grader_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
