# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0041_auto_20180709_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkgroup',
            name='deadline_miss',
            field=models.BooleanField(default=False),
        ),
    ]
