# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0042_homeworkgroup_deadline_miss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealgradermodel',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkgroup',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkgroupgrade',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peerevaluationmodel',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
