# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0043_auto_20180710_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehomeworkmodel',
            name='grade_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
