# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0044_auto_20180710_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_grading_type',
            field=models.TextField(null=True),
        ),
    ]
