# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-14 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0045_coursemodel_course_grading_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_function',
            field=models.TextField(null=True),
        ),
    ]
