# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-23 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0046_coursemodel_course_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehomeworkmodel',
            name='grade_rubric',
            field=models.IntegerField(null=True),
        ),
    ]
