# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-23 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0047_coursehomeworkmodel_grade_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehomeworkmodel',
            name='grade_rubric',
            field=models.TextField(null=True),
        ),
    ]
