# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0048_auto_20180923_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_group_type',
            field=models.TextField(default='shuffle'),
        ),
    ]
