# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0050_auto_20180925_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealgradermodel',
            name='override',
            field=models.BooleanField(default=False),
        ),
    ]
