# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-01 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0051_appealgradermodel_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkgroup',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
