# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-16 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0052_homeworkgroup_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkgroup',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
    ]
