# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-15 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0053_homeworkgroup_is_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehomeworkmodel',
            name='assignment_title',
            field=models.TextField(null=True),
        ),
    ]
