# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-15 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0054_coursehomeworkmodel_assignment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkgroup',
            name='group_name',
            field=models.TextField(null=True),
        ),
    ]
