# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-16 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0055_homeworkgroup_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorGradeOverRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseModel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.HomeworkGroup', to_field='group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructor_overwrite',
            },
        ),
    ]
