# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0056_instructorgradeoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehomeworkmodel',
            name='no_of_grader',
            field=models.TextField(null=True),
        ),
    ]
