# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0057_auto_20181220_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcombinationmodel',
            name='grader_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group2', to='instructor.HomeworkGroup', to_field='group'),
        ),
    ]
